/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NullSchema
 */
export interface NullSchema {
    /**
     * 
     * @type {any}
     * @memberof NullSchema
     */
    data: any | null;
}

/**
 * Check if a given object implements the NullSchema interface.
 */
export function instanceOfNullSchema(value: object): value is NullSchema {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NullSchemaFromJSON(json: any): NullSchema {
    return NullSchemaFromJSONTyped(json, false);
}

export function NullSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function NullSchemaToJSON(json: any): NullSchema {
    return NullSchemaToJSONTyped(json, false);
}

export function NullSchemaToJSONTyped(value?: NullSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

