/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Schema,
} from '../models/index';
import {
    SchemaFromJSON,
    SchemaToJSON,
} from '../models/index';

export interface RootPutRequest {
    body?: any | null;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async rootPutRaw(requestParameters: RootPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Schema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaFromJSON(jsonValue));
    }

    /**
     */
    async rootPut(requestParameters: RootPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Schema> {
        const response = await this.rootPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
